[project]
name = "mjml_py_mini_racer"
version = "0.0.1"
requires-python = ">=3.7"
dependencies = [
    "py-mini-racer==0.6.0"
]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
